#! /bin/bash

cargo build --release
cd target/release
sudo cp sdshell /bin
sudo echo '/usr/bin/sdshell' >> /etc/shells
sudo echo '/bin/sdshell' >> /etc/shells

mkdir sdshell/ ~/.config
mv sdsh.toml ~/.config/sdshell
